platform :ios, '11.0'

use_frameworks!

target 'DPLibrary_Example' do
  pod 'DPLibrary', :path => '../'

  target 'DPLibrary_Tests' do
    inherit! :search_paths
    
    pod 'KeychainSwift', '~> 19.0'
    pod 'Kingfisher', '~> 5.15.6'
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      if Gem::Version.new('9.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
